### PR TITLE
Replace XMPMetaParser for PDF files with a more reliable

### PR DESCRIPTION
**Pull request by brannow**

### CODE REVIEW

**Comment by brannow** [comment]
fixed issue https://github.com/xperseguers/t3ext-extractor/issues/7 and https://github.com/xperseguers/t3ext-extractor/issues/8

**Comment by brannow** [comment]
> Thanks for the PR. Generally speaking though, I'd like the code and commit messages to stick on the existing conventions (TYPO3 Core) used for the whole history of commits.

i don't see any problem in the code itself in terms of coding guidelines, the code is psr-4 conform. (same as the typo3 standard?)

because of the commit message style, if it's important to you, please at a node in the readme.md for other ppl like me.
If u don't like the format feel free to squash or just copy the code.

**Comment by xperseguers** [comment]
Will have a look, regarding the commit message and the rest, everything is documented, not in the README but in the full manual which is linked at the end of the README: https://docs.typo3.org/typo3cms/extensions/extractor/Links.html :)

**Comment by xperseguers** [comment]
PR has been rebased and merged.

**Pull request closed without merging**
